handle test failures gracefully (issue #11)

diff --git a/bin/debug_test b/bin/debug_test
--- a/bin/debug_test
+++ b/bin/debug_test
@@ -4,7 +4,18 @@
 
 container=nightwatch_grid_results
 
-docker-compose run --name $container -e DEBUG=true nightwatch \
-&& docker cp $container:/home/docker/app/tests_output . \
-&& docker rm -v $container
+function cleanup() {
+  exit_code=$?
+
+  docker cp $container:/home/docker/app/tests_output .
+  docker rm -fv $container > /dev/null
+
+  if [[ "$exit_code" == "1" ]]; then
+    printf "\n Test failure! View screenshots in tests_output/screenshots. \n"
+  fi
+}
+
+trap cleanup INT TERM EXIT
+
+docker-compose run --name $container -e DEBUG=true nightwatch
 
